const val introductionText1 = "Results-driven "
const val introductionText2 = " with a strong background in Android app development and a passion for creating seamless user experiences. Experienced in spearheading the design and development of innovative mobile applications, leveraging cutting-edge technologies and frameworks. Adept at leading small teams and collaborating cross-functionally to deliver high-quality products. Committed to staying abreast of industry trends and continuously improving technical skills."
const val email = "ayushpatel95@gmail.com"
const val linkedinLink = "https://linkedin.com/in/patelayush"
const val githubLink = "https://github.com/patelayush"
const val repo = "https://patelayush.github.io/Resume/"
const val resume_url = "Ayush_Patel_CV.pdf"
const val appname = "Bug-Free Bio"